[Viewer] map settings in discrete rates (Fix #177)
phylogeography/spread pull request #184
Opened 2022-02-18 12:49 UTC by jpmonettas

2022-02-21 22:23 UTC, fbielejec commented on src/cljs/analysis_viewer/views.cljs
> +   [:label "Transitions"] [switch-button {:id :transitions?}]
not needed, since there's no animation?

2022-02-21 22:25 UTC, fbielejec requested changes
no need for missiles switch, since this visualization is not animated

2022-02-22 10:58 UTC, jpmonettas commented
Good catch! Done!

2022-02-22 14:52 UTC, fbielejec approved these changes

2022-02-22 15:03 UTC, merged